# Generated by Django 5.2.3 on 2025-12-01 13:52
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0043_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='compliance_manager',
            field=models.ForeignKey(
                blank=True,
                help_text='履约主管',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='compliance_managed_contracts',
                to=settings.AUTH_USER_MODEL,
                verbose_name='compliance manager',
            ),
        ),
    ]
