# Generated by Django 5.2.6 on 2025-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0044_add_compliance_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
    ]
