# Generated by Django 5.2.6 on 2026-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0045_alter_contract_currency_alter_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
