# Generated by Django 5.2.6 on 2026-05-11 01:14

import django.db.models.deletion
import netbox_contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_contract', '0046_alter_contract_options_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='external_party_object_type',
            field=models.ForeignKey(blank=True, default=netbox_contract.models.get_default_external_party_type, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
