# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0048_revenuebillingrule_revenuecontract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuebillingrule',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('month', '\u6708\u5ea6'), ('quarter', '\u5b63\u5ea6'), ('year', '\u5e74\u5ea6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuebillingrule',
            name='billing_direction',
            field=models.CharField(blank=True, choices=[('postpay', '\u540e\u4ed8'), ('prepay', '\u9884\u4ed8')], max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuebillingrule',
            name='proration_rule',
            field=models.CharField(choices=[('actual_days', '\u6309\u5b9e\u9645\u5929\u6570'), ('full_month', '\u6309\u6574\u6708'), ('none', '\u4e0d\u6298\u7b97')], max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuebillingrule',
            name='rounding_precision',
            field=models.CharField(choices=[('0', '\u4fdd\u75590\u4f4d'), ('1', '\u4fdd\u75591\u4f4d'), ('2', '\u4fdd\u75592\u4f4d')], max_length=20),
        ),
        migrations.AlterField(
            model_name='revenuebillingrule',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('activation', '\u5f00\u901a'), ('acceptance', '\u9a8c\u6536'), ('delivery', '\u4ea4\u4ed8')], max_length=50),
        ),
    ]
