# Generated by Codex on 2026-07-09

from django.db import migrations, models


SOURCE_SYSTEM_CHOICES = [
    ('SAMPLE_DATA', '样例数据'),
    ('REVENUE_SYS', '收入系统'),
    ('BANK_FLOW', '银行流水'),
]

ENTITY_TYPE_CHOICES = [
    ('RevenueCustomer', '客户'),
    ('RevenueProject', '项目'),
    ('RevenueContract', '收入合同'),
    ('RevenueContractVersion', '合同版本'),
    ('RevenueContractLine', '合同项'),
    ('RevenueBillingRule', '计费规则'),
    ('RevenueReceivableBill', '应收账单'),
    ('RevenueReceivableLine', '应收明细'),
    ('RevenueInvoice', '发票'),
    ('RevenueInvoiceLine', '发票明细'),
    ('RevenueInvoiceMapping', '发票映射'),
    ('RevenueReceipt', '回款'),
    ('RevenueReceiptAllocation', '回款分配'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0049_revenue_billing_rule_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuebillingsegment',
            name='change_trigger',
            field=models.CharField(choices=[('normal', '正常计费'), ('contract_change', '合同变更'), ('price_change', '价格调整')], max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuecontract',
            name='source_system',
            field=models.CharField(choices=SOURCE_SYSTEM_CHOICES, max_length=50),
        ),
        migrations.AlterField(
            model_name='revenueinvoice',
            name='source_system',
            field=models.CharField(choices=SOURCE_SYSTEM_CHOICES, max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuereceipt',
            name='source_system',
            field=models.CharField(choices=SOURCE_SYSTEM_CHOICES, max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuesynclog',
            name='entity_type',
            field=models.CharField(choices=ENTITY_TYPE_CHOICES, max_length=50),
        ),
        migrations.AlterField(
            model_name='revenuesynclog',
            name='source_system',
            field=models.CharField(choices=SOURCE_SYSTEM_CHOICES, max_length=50),
        ),
    ]
