# Generated by Codex on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


def delete_prepayment_receipt_allocations(apps, schema_editor):
    receipt_allocation = apps.get_model('netbox_contract', 'RevenueReceiptAllocation')
    receipt_allocation.objects.filter(receivable_line__isnull=True).delete()
    receipt_allocation.objects.filter(allocation_type='deposit_prepayment').delete()


def delete_prepayment_sync_logs(apps, schema_editor):
    sync_log = apps.get_model('netbox_contract', 'RevenueSyncLog')
    sync_log.objects.filter(entity_type__in=['RevenuePrepaymentAccount', 'RevenuePrepaymentAllocation']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0050_revenue_remaining_choice_fields'),
    ]

    operations = [
        migrations.RunPython(delete_prepayment_receipt_allocations, migrations.RunPython.noop),
        migrations.RunPython(delete_prepayment_sync_logs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='revenuereceiptallocation',
            name='prepayment_account',
        ),
        migrations.AlterField(
            model_name='revenuereceiptallocation',
            name='receivable_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='netbox_contract.revenuereceivableline'),
        ),
        migrations.DeleteModel(
            name='RevenuePrepaymentAllocation',
        ),
        migrations.DeleteModel(
            name='RevenuePrepaymentAccount',
        ),
    ]
