# Generated by Codex on 2026-07-10

from django.db import migrations, models


ENTITY_TYPE_CHOICES = [
    ('RevenueCustomer', '客户'),
    ('RevenueProject', '项目'),
    ('RevenueContract', '收入合同'),
    ('RevenueContractVersion', '合同版本'),
    ('RevenueContractLine', '合同项'),
    ('RevenueBillingRule', '计费规则'),
    ('RevenueReceivableBill', '应收账单'),
    ('RevenueReceivableLine', '应收明细'),
    ('RevenueInvoice', '发票'),
    ('RevenueInvoiceLine', '发票明细'),
    ('RevenueInvoiceMapping', '发票映射'),
    ('RevenueReceipt', '回款'),
    ('RevenueReceiptAllocation', '回款分配'),
]


def delete_adjustment_sync_logs(apps, schema_editor):
    sync_log = apps.get_model('netbox_contract', 'RevenueSyncLog')
    sync_log.objects.filter(entity_type__in=['RevenueAdjustment', 'RevenueAdjustmentAllocation']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0051_remove_revenue_prepayment'),
    ]

    operations = [
        migrations.RunPython(delete_adjustment_sync_logs, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='RevenueAdjustmentAllocation',
        ),
        migrations.DeleteModel(
            name='RevenueAdjustment',
        ),
        migrations.AlterField(
            model_name='revenuesynclog',
            name='entity_type',
            field=models.CharField(choices=ENTITY_TYPE_CHOICES, max_length=50),
        ),
    ]
