# Generated by Django 6.0.5 on 2026-07-14 07:42

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_contract', '0052_remove_revenue_adjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueReceivablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('plan_code', models.CharField(max_length=100, unique=True)),
                ('charge_item', models.CharField(max_length=200)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('billing_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_plans', to='netbox_contract.revenuebillingrule')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_plans', to='netbox_contract.revenuecontract')),
                ('contract_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_plans', to='netbox_contract.revenuecontractline')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '收入应收计划',
                'verbose_name_plural': '收入应收计划',
                'ordering': ('contract', 'plan_code'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RevenueReceivablePlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('version_no', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_event', models.CharField(blank=True, max_length=50)),
                ('offset_days', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_from', models.DateField()),
                ('change_reason', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='netbox_contract.revenuereceivableplan')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '收入应收计划版本',
                'verbose_name_plural': '收入应收计划版本',
                'ordering': ('plan', 'version_no'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RevenueTriggerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('trigger_event', models.CharField(max_length=50)),
                ('actual_trigger_date', models.DateField()),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('source_system', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_records', to='netbox_contract.revenuereceivableplan')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trigger_records', to='netbox_contract.revenuereceivableplanversion')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': '收入应收触发记录',
                'verbose_name_plural': '收入应收触发记录',
                'ordering': ('plan', '-actual_trigger_date'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RevenueAdjustmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('adjustment_type', models.CharField(max_length=50)),
                ('adjustment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('source_system', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('receivable_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_records', to='netbox_contract.revenuereceivableline')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='netbox_contract.revenuereceivableplan')),
            ],
            options={
                'verbose_name': '收入应收调整记录',
                'verbose_name_plural': '收入应收调整记录',
                'ordering': ('-adjustment_date', '-created'),
                'constraints': [models.CheckConstraint(condition=models.Q(('plan__isnull', False), ('receivable_line__isnull', False), _connector='OR'), name='revenue_adjustment_has_target'), models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lt', 0), _connector='OR'), name='revenue_adjustment_nonzero')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='revenuereceivableplanversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version_no'), name='unique_revenue_plan_version_no'),
        ),
        migrations.AddConstraint(
            model_name='revenuereceivableplanversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('plan',), name='unique_current_revenue_plan_version'),
        ),
    ]
